<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-07-13T18:22:34 EDT" name="Suite" finished-at="2023-07-13T18:22:38 EDT" duration-ms="4078">
    <groups>
    </groups>
    <test started-at="2023-07-13T18:22:34 EDT" name="PriceChangeValidation" finished-at="2023-07-13T18:22:36 EDT" duration-ms="2043">
      <class name="test.PriceChange_Validation">
        <test-method signature="PriceChangeValidation_24H()[pri:0, instance:test.PriceChange_Validation@61862a7f]" started-at="2023-07-13T18:22:34 EDT" name="PriceChangeValidation_24H" finished-at="2023-07-13T18:22:36 EDT" duration-ms="2005" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- PriceChangeValidation_24H -->
      </class> <!-- test.PriceChange_Validation -->
    </test> <!-- PriceChangeValidation -->
    <test started-at="2023-07-13T18:22:36 EDT" name="PriceValidation" finished-at="2023-07-13T18:22:37 EDT" duration-ms="462">
      <class name="test.PriceValidation">
        <test-method signature="BTC_ETH_PriceValidation()[pri:0, instance:test.PriceValidation@5c33f1a9]" started-at="2023-07-13T18:22:36 EDT" name="BTC_ETH_PriceValidation" finished-at="2023-07-13T18:22:37 EDT" duration-ms="459" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
Test is failed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
Test is failed expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:46)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:30)
at test.PriceValidation.BTC_ETH_PriceValidation(PriceValidation.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BTC_ETH_PriceValidation -->
      </class> <!-- test.PriceValidation -->
    </test> <!-- PriceValidation -->
    <test started-at="2023-07-13T18:22:37 EDT" name="Filter_BTC_ETH" finished-at="2023-07-13T18:22:37 EDT" duration-ms="552">
      <class name="test.Filter_BTC_ETH_Assets">
        <test-method signature="FilterAssests()[pri:0, instance:test.Filter_BTC_ETH_Assets@4ec4f3a0]" started-at="2023-07-13T18:22:37 EDT" name="FilterAssests" finished-at="2023-07-13T18:22:37 EDT" duration-ms="549" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- FilterAssests -->
      </class> <!-- test.Filter_BTC_ETH_Assets -->
    </test> <!-- Filter_BTC_ETH -->
    <test started-at="2023-07-13T18:22:37 EDT" name="SchemaValidation" finished-at="2023-07-13T18:22:38 EDT" duration-ms="947">
      <class name="test.SchemaValidation">
        <test-method signature="ValidateSchema()[pri:0, instance:test.SchemaValidation@747ddf94]" started-at="2023-07-13T18:22:37 EDT" name="ValidateSchema" finished-at="2023-07-13T18:22:38 EDT" duration-ms="945" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ValidateSchema -->
      </class> <!-- test.SchemaValidation -->
    </test> <!-- SchemaValidation -->
  </suite> <!-- Suite -->
</testng-results>
